### ISSUE TITLE
Load the bundle in prod env

### ISSUE THREAD

**Issue by iamluc** [pinkfire/PinkfireBundle#4]
... then active on demand.

We could have a parameter like:

``` yaml
pinkfire:
    activation: always|ondemand
```

the ondemand mode could listen a special route or a special query parameter (which must be protected !) to activate.

**Comment by csarrazi** [comment]
``` yml
pinkfire:
    activation_strategy: always|cookie|query
    # query-only option
    parameter: _pinkfire
    # cookie-only options
    cookie: pinkfire
    delete_cookie_on_next_query: false
```

What do you think about this?
